import os
from dotenv import load_dotenv
from crewai import Agent, Task, Crew, LLM
import logging

# Load environment variables
load_dotenv()

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Initialize Gemini LLM
def setup_llm():
    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        logging.error("GOOGLE_API_KEY is not set.")
        raise EnvironmentError("GOOGLE_API_KEY is required.")

    return LLM(
        model="gemini/gemini-1.5-pro-latest",
        temperature=0.5,
        api_key=api_key
    )

# === Agents ===
def create_ba_agent(llm):
    return Agent(
        role="Business Analyst",
        goal="Translate high-level requirements into clear user stories using predefined templates",
        backstory="You are a detail-oriented Business Analyst with experience writing user stories that align with Agile practices.",
        verbose=True,
        llm=llm
    )

def create_dev_agent(llm):
    return Agent(
        role="Developer",
        goal="Write clean, working code based on user stories and existing templates",
        backstory="You are a senior software developer focused on converting user stories into working code solutions.",
        verbose=True,
        llm=llm
    )

def create_tester_agent(llm):
    return Agent(
        role="Tester",
        goal="Write and execute test cases based on business requirements and code",
        backstory="You are a QA engineer experienced in writing functional test cases and reporting bugs.",
        verbose=True,
        llm=llm
    )

# === Simulation Pipeline ===
def simulate_project_pipeline(requirement):
    llm = setup_llm()
    
    # Step 1: Business Analyst
    ba_agent = create_ba_agent(llm)
    ba_task = Task(
        description=f"""
        Convert the following high-level business requirement into user stories using a predefined Agile template:

        Requirement: {requirement}

        Format each story using: "As a [role], I want [feature] so that [benefit]."
        """,
        agent=ba_agent,
        expected_output="List of well-defined user stories"
    )

    # Step 2: Developer
    dev_agent = create_dev_agent(llm)
    dev_task = Task(
        description="""
        Based on the user stories generated by the Business Analyst, write Python code that implements the described functionality.
        Ensure the code is clean, commented, and executable.
        """,
        agent=dev_agent,
        expected_output="Complete Python code implementation"
    )

    # Step 3: Tester
    tester_agent = create_tester_agent(llm)
    tester_task = Task(
        description="""
        Based on the code and user stories, write a set of test cases (preferably in Gherkin or plain English).
        Validate that the functionality meets all the user stories.
        """,
        agent=tester_agent,
        expected_output="Well-written test cases"
    )

    # Run as a Crew
    crew = Crew(
        agents=[ba_agent, dev_agent, tester_agent],
        tasks=[ba_task, dev_task, tester_task],
        verbose=True
    )

    result = crew.kickoff()

    # Combine artifacts into a structured output
    return {
        "user_stories": ba_task.output,
        "code": dev_task.output,
        "test_cases": tester_task.output
    }

# === Project Lead Chatbot ===
def project_lead_query(question):
    llm = setup_llm()
    
    pm_agent = Agent(
        role="Project Manager Assistant",
        goal="Answer questions about project artifacts (user stories, code, test cases)",
        backstory="You are the project lead assistant with access to all current artifacts. You're responsible for reporting the status and quality of each.",
        verbose=True,
        llm=llm
    )

    pm_task = Task(
        description=f"""
        You are the project manager. Given this question:

        "{question}"

        Respond based on your knowledge of recent project artifacts.
        Include your reasoning and conclusions clearly.
        """,
        agent=pm_agent,
        expected_output="A thoughtful and concise response to the project manager"
    )

    crew = Crew(
        agents=[pm_agent],
        tasks=[pm_task],
        verbose=True
    )

    result = crew.kickoff()
    return pm_task.output
